export const APP_NAVIGATION_SECTIONS_WIDTH = 65;
export const APP_NAVIGATION_SECTION_INITIAL_WIDTH = 260;
export const APP_NAVIGATION_SECTION_MIN_WIDTH = 200;

export const ARTICLE_FULL_EDITOR_INITIAL_WIDTH = 957;
export const ASSET_FULL_EDITOR_INITIAL_WIDTH = 800;
export const ASSET_FULL_EDITOR_MIN_WIDTH = 360;
